# Generated by Django 3.1.5 on 2021-03-10 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=64)),
                ('Content', models.CharField(max_length=256)),
                ('CreatedDate', models.DateTimeField(default=datetime.datetime(2021, 3, 10, 20, 34, 4, 638288))),
                ('Budget', models.FloatField()),
                ('Status', models.BooleanField(default=True)),
            ],
        ),
    ]
