# Generated by Django 3.1.5 on 2021-03-10 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0002_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 20, 41, 46, 977879)),
        ),
    ]
