# Generated by Django 3.1.5 on 2021-03-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0004_auto_20210310_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='CreatedDate',
            field=models.DateTimeField(),
        ),
    ]
