# Generated by Django 3.1.5 on 2021-03-24 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0006_auto_20210310_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 24, 21, 54, 23, 508388)),
        ),
    ]
